[control_plane]
control ansible_host=151.248.113.234 node_hostname=k8s-control-plane

[workers]
worker ansible_host=151.248.113.189 node_hostname=k8s-worker

[k8s:children]
control_plane
workers

[k8s:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/ansible-k8s
ansible_python_interpreter=/usr/bin/python3.12
